from enum import Enum


class LociType(Enum):
    INITIAL_MEASURE = 0
    DEFAULT = 1
    ANTEPENULTIMATE_TO_PENULTIMATE_MEASURE = 2
    PENULTIMATE_MEASURE = 3
    PENULTIMATE_TO_FINAL_MEASURE = 4
    FINAL_MEASURE = 5
