from enum import IntEnum


class LociType(IntEnum):
    DEFAULT = 0
    INITIAL_MEASURE = 1
    ANTEPENULTIMATE_TO_PENULTIMATE_MEASURE = 2
    PENULTIMATE_MEASURE = 3
    PENULTIMATE_TO_FINAL_MEASURE = 4
    FINAL_MEASURE = 5
